### ISSUE TITLE
running infer.sample.py out of memory error

### ISSUE THREAD

**Issue by Xcodingman** [facebookresearch/Detectron#57] opened 2018-01-28 09:25 UTC
INFO net.py: 125: res4_3_branch2c_b preserved in workspace (unused)
I0128 17:20:08.529714  5211 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 0.000198165 secs
I0128 17:20:08.530056  5211 net_dag.cc:61] Number of parallel execution chains 63 Number of operators = 402
I0128 17:20:08.554688  5211 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 0.000179959 secs
I0128 17:20:08.554926  5211 net_dag.cc:61] Number of parallel execution chains 30 Number of operators = 358
I0128 17:20:08.556850  5211 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 1.3319e-05 secs
I0128 17:20:08.556897  5211 net_dag.cc:61] Number of parallel execution chains 5 Number of operators = 18
INFO infer_simple.py: 111: Processing demo/33823288584_1d21cf0a26_k.jpg -> /tmp/detectron-visualizations/33823288584_1d21cf0a26_k.jpg.pdf
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /home/saxon/caffe2/caffe2/core/context_gpu.cu:343: out of memory Error from operator: 
input: "gpu_0/res3_3_branch2c" input: "gpu_0/res3_3_branch2c_bn_s" input: "gpu_0/res3_3_branch2c_bn_b" output: "gpu_0/res3_3_branch2c_bn" name: "" type: "AffineChannel" device_option { device_type: 1 cuda_gpu_id: 0 }

**Comment by rbgirshick** [comment] 2018-01-28 16:27
Duplicate of #21.

**Closed by rbgirshick** 2018-01-28 16:27 UTC
Labels: duplicate
