### ISSUE TITLE
convert trained model (.pkl) to caffe2 model (.pb)

### ISSUE THREAD

**Issue by fxs628** [facebookresearch/Detectron#253] opened 2018-03-08 13:30 UTC
Hi, 
     I have trained a retinanet on my custom dataset and now get a  model_final.pkl. I  convert it to standard caffe2 model (.pb) using the script named convert_pkl_to_pb.py, and got error follows :
**"FPN not supported."
"RetinaNet model not supported."**

I wonder if  any model using FPN, RetinaNet, Mask or KeyPoint and the script convert_pkl_to_pb.py will run failed?
If so, how can I convert my trained model to caffe2 model(.pb)?

Appreciate any help! 
thanks!

**Comment by rbgirshick** [comment] 2018-03-08 15:29
Duplicate of #134.

**Closed by rbgirshick** 2018-03-08 15:29 UTC
Labels: duplicate
