### ISSUE TITLE
Why the results of model zoo are mostly higher than paper reporting？

### ISSUE THREAD

**Issue by PhyscalX** [facebookresearch/Detectron#298] opened 2018-03-17 08:19 UTC
I tried to replicate the  Faster R-CNN(FPN)/Mask R-CNN(FPN), yet only got the similar results as the reporting of paper(Note that almost results in the ModelZoo are higher about 2~3 mAP). 

Are there any tricks that used after submitting of paper? 
(I have used: (800, 1333) and NMS=0.5)

**Comment by rbgirshick** [comment] 2018-03-17 18:36
The improvements are due to:
(1) NMS threshold 0.5
(2) End-to-end training
(3) But fix in bbox regression

You didn't specify what you "tried", so it's impossible to address your issue. Closing.

**Closed by rbgirshick** 2018-03-17 18:36 UTC
