### ISSUE TITLE
Is TITAN X Pascal supported

### ISSUE THREAD

**Issue by deeprun** [facebookresearch/Detectron#271] opened 2018-03-10 22:15 UTC
When I built the ops, I got the following error:

CMake Error at cmake/Cuda.cmake:32 (message):
  Invalid CUDA_ARCH_NAME, supported values: Kepler, Maxwell, Pascal, Volta,
  All, Manual.  Got Auto

I am currently have a TITAN X Pascal, is that supported?

**Comment by rbgirshick** [comment] 2018-03-11 00:50
Duplicate of #251.

**Closed by rbgirshick** 2018-03-11 00:50 UTC
