### ISSUE TITLE
 AssertionError: Unexpected value for NUM_GPUS. Make sure you are not running single-GPU inference with NUM_GPUS > 1.

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#491] opened 2018-06-12 08:43 UTC
hi!
In yaml :
NUM_GPUS : 4
I train with 4 GPUS：
`CUDA_VISIBLE_DEVICES=4,5,6,7 python2 tools/train_net.py --cfg experiment/configs/e2e_faster_rcnn_R-18-FPN_2x.yaml OUTPUT_DIR output/detectron-output
`
it encounters the error:
Traceback (most recent call last):
  File "tools/train_net.py", line 128, in <module>
    main()
  File "tools/train_net.py", line 110, in main
    checkpoints = detectron.utils.train.train_model()
  File "/data/chuli/detectron/detectron/utils/train.py", line 58, in train_model
    setup_model_for_training(model, weights_file, output_dir)
  File "/data/chuli/detectron/detectron/utils/train.py", line 164, in setup_model_for_training
    nu.broadcast_parameters(model)
  File "/data/chuli/detectron/detectron/utils/net.py", line 193, in broadcast_parameters
    _do_broadcast(model.params)
  File "/data/chuli/detectron/detectron/utils/net.py", line 181, in _do_broadcast
    ('Unexpected value for NUM_GPUS. Make sure you are not '
AssertionError: Unexpected value for NUM_GPUS. Make sure you are not running single-GPU inference with NUM_GPUS > 1.

What's wrong? thanks!

**Comment by gadcam** [comment] 2018-06-12 09:41
@lilichu 
Did you try to print the value of <code>len(all_blobs)</code> and <code>cfg.NUM_GPUS</code> just before this line ?

https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/utils/net.py#L180
If you have these values you could guess on what side is the problem.

**Comment by lilichu** [comment] 2018-06-12 10:01
@gadcam 
well, it print:  len(all_blobs) = 363,  cfg.NUM_GPUS = 4
what does it mean?  thanks!

**Comment by gadcam** [comment] 2018-06-12 12:23
@lilichu I am not familiar with this sort of problems.
The only thing I can say is that <code>NUM_GPUS</code> is correctly propagated here.
But looks like <code>model.params</code> is not well initialized as its length is not good.

>e2e_faster_rcnn_R-18-FPN_2x.yaml

Looks like you are using a custom backbone & config file.
Maybe the implementation of the new backbone you added is not good or the CFG file does not reflect what you implemented.
And so it is not doing the correct thing when it hit
https://github.com/facebookresearch/Detectron/blob/b5dada9b8e8ecfb240b8045233040497cd7b794b/detectron/utils/train.py#L132
I think we can not help you much because it seems the problem is on some custom code.

**Comment by lilichu** [comment] 2018-06-14 06:56
thanks a lot!
The error is from my ResNet-18 structrue code. I have solved it, thanks!

**Comment by gadcam** [comment] 2018-06-14 10:38
@lilichu I did nothing :) I think you can close the issue if the problem is gone!

**Closed** 2018-06-14 12:10 UTC
