### ISSUE TITLE
OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZN6caffe28TypeMeta2IdINS_6TensorINS_11CUDAContextEEEEENS_11CaffeTypeIdEv

### ISSUE THREAD

**Issue by 7crystle7** [facebookresearch/Detectron#518] opened 2018-06-23 11:01 UTC
After I install caffe2, I install detectron package following the instruction of the official website. There is no error when I make and install it. Then I run the code 'test_spatial_narrow_as_op.py' and there are errors:

Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
 File "detectron/tests/test_spatial_narrow_as_op.py", line 88, in <module>
   c2_utils.import_detectron_ops()
 File "/home/neuron/PycharmProjects/Detectron/detectron/utils/c2.py", line 42, in import_detectron_ops
   dyndep.InitOpsLibrary(detectron_ops_lib)
 File "/home/neuron/anaconda3/envs/maskrcnnp2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
   _init_impl(name)
 File "/home/neuron/anaconda3/envs/maskrcnnp2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
   ctypes.CDLL(path)
 File "/home/neuron/anaconda3/envs/maskrcnnp2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
   self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZN6caffe28TypeMeta2IdINS_6TensorINS_11CUDAContextEEEEENS_11Caffe

### Detailed steps to reproduce

I have already installed caffe2 successfully following the official instruction and the two test code. Now, when I run python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure" , the result is success and when I run python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())', the result is the exact number of my gpu devices. I have noticed there are some similar issues and they solved the problem by adding the python path to where the caffe2 is build. However, I install caffe2 using conda install. Thus I can not find where the build folder is.

### System information

* Operating system: ubuntu 16.04
* Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609  
* CUDA version: 8.0
* cuDNN version: 7.1.4
* NVIDIA driver version: 384.13
* GPU models (for all devices if they are not all the same):  1080ti
* `PYTHONPATH` environment variable: 
export PYTHONPATH=/usr/local:$PYTHONPATH
export PYTHONPATH=/home/my/anaconda3/envs/maskrcnnp2/lib/python2.7/site-packages/caffe2/python:$PYTHONPATH
export LD_LIBRARY_PATH=/home/my/anaconda3/envs/maskrcnnp2/lib:$LD_LIBRARY_PATH
* `python --version` output: 2.7 in Anaconda
* Anything else that seems relevant: I install these package in the virtualenv of anaconda and maskrcnn2 is its name. I have already type these paths to bashrc by running: 'gedit ~/.bashrc' in the virtualenv and then running 'source ~/.bashrc'. I am not sure if I add a wrong path or there is something wrong with my operation.

**Comment by 7crystle7** [comment] 2018-06-24 08:16
When I use source code to make and install caffe2 following the official instruction, such error disappear. But I will still open this issue in case someone is able to solve the problem when using conda install caffe2.

**Comment by ir413** [comment] 2018-06-24 19:54
Duplicate of #502.

**Closed by ir413** 2018-06-24 19:54 UTC
