### ISSUE TITLE
coco_2gpu train failed

### ISSUE THREAD

**Issue by zhcf** [facebookresearch/Detectron#160] opened 2018-02-16 12:07 UTC
Actual results
E0216 06:57:36.106158  4415 pybind_state.h:422] Exception encountered running PythonOp function: RuntimeError: [enforce fail at context_gpu.h:307] error == cudaSuccess. 77 vs 0. Error at: /opt/caffe2/caffe2/core/context_gpu.h:307: an illegal memory access was encountered 

At:
  /opt/project/detectron/lib/utils/blob.py(128): py_op_copy_blob
  /opt/project/detectron/lib/ops/collect_and_distribute_fpn_rpn_proposals.py(62): forward
terminate called after throwing an instance of 'terminate called recursively
terminate called recursively
caffe2::EnforceNotMet'
*** Aborted at 1518782256 (unix time) try "date -d @1518782256" if you are using GNU date ***
terminate called recursively
  what():  [enforce fail at context_gpu.h:170] . Encountered CUDA error: an illegal memory access was encountered Error from operator: 
input: "gpu_0/rpn_cls_logits_fpn2_b_grad" input: "gpu_1/rpn_cls_logits_fpn2_b_grad" output: "gpu_0/rpn_cls_logits_fpn2_b_grad" name: "" type: "Add" device_option { device_type: 1 cuda_gpu_id: 0 }
terminate called recursively
PC: @     0x7f4de4d401f7 __GI_raise
*** SIGABRT (@0x10a0) received by PID 4256 (TID 0x7f4c3bfff700) from PID 4256; stack trace: ***
    @     0x7f4de57e65e0 (unknown)
    @     0x7f4de4d401f7 __GI_raise
    @     0x7f4de4d418e8 __GI_abort
    @     0x7f4dde319a55 (unknown)
    @     0x7f4dde317a36 (unknown)
    @     0x7f4dde317a63 (unknown)
E0216 06:57:36.121296  4412 pybind_state.h:422] Exception encountered running PythonOp function: RuntimeError: [enforce fail at context_gpu.h:307] error == cudaSuccess. 77 vs 0. Error at: /opt/caffe2/caffe2/core/context_gpu.h:307: an illegal memory access was encountered 

At:
  /opt/project/detectron/lib/ops/generate_proposals.py(101): forward
terminate called recursively
    @     0x7f4dde36e345 (unknown)
    @     0x7f4de57dee25 start_thread
    @     0x7f4de4e0334d __clone

Detailed steps to reproduce
cd /opt/project/detectron
python2 tools/train_net.py --multi-gpu-testing
--cfg configs/getting_started/tutorial_2gpu_e2e_faster_rcnn_R-50-FPN.yaml 
OUTPUT_DIR work/output/coco_train_with_2gpu

System information
Operating system: redhat7.3

Compiler version: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

CUDA version: 8.0, cuda_8.0.61_375.26_linux-run

cuDNN version: cudnn-8.0-linux-x64-v7

NVIDIA driver version: 375.26

GPU models (for all devices if they are not all the same): Fri Feb 9 11:11:55 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26 Driver Version: 375.26 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 TITAN X (Pascal) Off | 0000:1B:00.0 Off | N/A |
| 23% 22C P8 9W / 250W | 2MiB / 12189MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 TITAN X (Pascal) Off | 0000:86:00.0 Off | N/A |
| 32% 55C P2 105W / 250W | 347MiB / 12189MiB | 94% Default |
+-------------------------------+----------------------+----------------------+

PYTHONPATH environment variable: /opt/project/detectron/lib:/opt/caffe2/build

python --version output: Python 2.7.5

**Comment by oujieww** [comment] 2018-02-25 04:28
I get this problem ,too

**Comment by rbgirshick** [comment] 2018-02-25 16:09
Duplicate of #32 (illegal memory access in Caffe2 Add op). Closing to consolidate this bug into issue #32.

**Closed by rbgirshick** 2018-02-25 16:09 UTC
Labels: duplicate
