### ISSUE TITLE
.pdf format

### ISSUE THREAD

**Issue by moulei007** [facebookresearch/Detectron#357] opened 2018-04-11 07:41 UTC
I want to  save my results in .jpg format, then , where should I change in the source code?

**Comment by moulei007** [comment] 2018-04-11 08:29
After a careful view at source code, I finally  convert .pdf format into .png format.

**Comment by ir413** [comment] 2018-04-11 10:40
Duplicate of #344

**Closed by ir413** 2018-04-11 10:40 UTC

**Comment by aishoushi** [comment] 2019-03-14 05:50
Hi, when I use infer_simple.py, it turns out such problem:
I/O Error: Couldn't open file 'infer_outputs/.pdf': No such file or directory.
Syntax Error: Could not merge damaged documents ('infer_outputs/.pdf')
why is it? @gadcam
