### ISSUE TITLE
Does facebook have plan to release a Pytorch 1.0 version Detectron?

### ISSUE THREAD

**Issue by ArchNew** [facebookresearch/Detectron#681] opened 2018-09-25 07:01 UTC
Rumor is, Facebook is secretly re-writing Detectron using Pytorch 1.0. I'm hoping it's true because Pytorch is much easier to use than caffe2.

**Comment by ir413** [comment] 2018-09-25 12:27
Duplicate of #70 and #375.

**Closed by ir413** 2018-09-25 12:27 UTC
