### ISSUE TITLE
Error while running vis_one_image_opencv()

### ISSUE THREAD

**Issue by aayushahuja** [facebookresearch/Detectron#119] opened 2018-02-07 06:11 UTC
https://github.com/facebookresearch/Detectron/blob/021685d42f7e8ac097e2bcf79fecb645f211378e/lib/utils/vis.py#L107

Get the following error:
    106     if show_border:
    107         contours, _ = cv2.findContours(
--> 108             mask.copy(), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
    109         cv2.drawContours(img, contours, -1, _WHITE, border_thick, cv2.LINE_AA)
    110 

ValueError: too many values to unpack

it should be _, contours, _ according to the definition : 
im2, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

**Comment by ppwwyyxx** [comment] 2018-02-07 06:21
Duplicate of #9

**Closed** 2018-02-08 03:19 UTC

**Comment by aishwaryap** [comment] 2019-03-27 21:10
With opencv 4.0.0 the [convention](https://docs.opencv.org/4.0.0/d4/d73/tutorial_py_contours_begin.html) seems to have changed again so the fix in [#9](https://github.com/facebookresearch/Detectron/pull/9) breaks. Downgrading to 3.2.0 fixed it for me. It would be good to reflect this in the requirements.
