### ISSUE TITLE
how to visualize the network structure?

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#472] opened 2018-06-05 03:34 UTC
hi!

I trained my network(resnet18), how to visualize the network structure?  thanks!

**Comment by gadcam** [comment] 2018-06-05 07:54
Duplicate of #320.
I think you should read this comment https://github.com/facebookresearch/Detectron/issues/320#issuecomment-377419650

**Closed** 2018-06-05 12:48 UTC
