### ISSUE TITLE
when i run mask-rcnn,i met the problem as follow,canyou help me .....Aborted at 1536193538 (unix time) try "date -d @1536193538" if you are using GNU date *** PC: @     0x7f17edf37545 (unknown)

### ISSUE THREAD

**Issue by shenghsiaowong** [facebookresearch/Detectron#651] opened 2018-09-06 00:41 UTC
json_stats: {"accuracy_cls": 1.000000, "eta": "2:37:02", "iter": 6160, "loss": 0.047840, "loss_bbox": 0.000511, "loss_cls": 0.000934, "loss_mask": 0.033317, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.004061, "loss_rpn_bbox_fpn4": 0.000000, "loss_rpn_bbox_fpn5": 0.000000, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000005, "loss_rpn_cls_fpn3": 0.011109, "loss_rpn_cls_fpn4": 0.000003, "loss_rpn_cls_fpn5": 0.000000, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 2873, "time": 0.175014}
*** Aborted at 1536193538 (unix time) try "date -d @1536193538" if you are using GNU date ***
PC: @     0x7f17edf37545 (unknown)
*** SIGSEGV (@0x0) received by PID 6756 (TID 0x7f16763ff700) from PID 0; stack trace: ***
    @     0x7f17ee290390 (unknown)
    @     0x7f17edf37545 (unknown)
    @     0x7f17edf39184 __libc_malloc
    @     0x7f17e4d05945 (unknown)
    @     0x7f17e4d077ab (unknown)
    @     0x7f17be71491f (unknown)
    @     0x7f17be71546e (unknown)
    @           0x4ae223 PyObject_CallFunctionObjArgs
    @     0x7f17e4d15de7 (unknown)
    @           0x4ffad2 (unknown)
    @           0x547626 PyNumber_TrueDivide
    @           0x4be9cb PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4c136f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4d54b9 (unknown)
    @           0x4eebee (unknown)
    @           0x4a577e PyObject_Call
    @           0x4c5e10 PyEval_CallObjectWithKeywords
    @     0x7f17b9535159 pybind11::detail::object_api<>::operator()<>()
    @     0x7f17b9536f22 caffe2::python::PythonOpBase<>::RunOnDevice()
    @     0x7f17b95340e3 caffe2::Operator<>::Run()
    @     0x7f17b9564a27 _ZN6caffe213GPUFallbackOpINS_6python8PythonOpINS_10CPUContextELb0EEENS_11SkipIndicesIJEEEE11RunOnDeviceEv
    @     0x7f17b9562f9d caffe2::Operator<>::RunAsync()
    @     0x7f17b84d4468 caffe2::AsyncNetBase::run()
    @     0x7f17b84e8287 _ZZN6caffe218AsyncSchedulingNet8scheduleEibENKUlvE_clEv
    @     0x7f17b84d8fd4 caffe2::TaskThreadPool::main_loop()
    @     0x7f17e75bac80 (unknown)
    @     0x7f17ee2866ba start_thread
    @     0x7f17edfbc41d clone
    @                0x0 (unknown)

* Operating system: ubuntu16.04
* Compiler version: gcc5.0
* CUDA version: 9.0
* cuDNN version: 7.0.1
* NVIDIA driver version: 390
* `PYTHONPATH` environment variable: 2.7

**Comment by ir413** [comment] 2018-09-18 17:31
Closing as this seems like a duplicate of #578.

**Closed by ir413** 2018-09-18 17:31 UTC
