### ISSUE TITLE
docker install problem

### ISSUE THREAD

**Issue by hxtkyne** [facebookresearch/Detectron#570] opened 2018-07-16 13:45 UTC
$ docker build -t detectron:c2-cuda9-cudnn7 .
Sending build context to Docker daemon  4.096kB
Step 1/15 : FROM caffe2/caffe2:snapshot-py2-cuda9.0-cudnn7-ubuntu16.04
 ---> 9ae3e8ea7508
Step 2/15 : RUN mkdir /usr/local/caffe2_build
 ---> Using cache
 ---> 2ffe122b66af
Step 3/15 : RUN cd /usr/local/caffe2
 ---> Using cache
 ---> 7330545a1616
Step 4/15 : RUN mv * /usr/local/caffe2_build
 ---> Running in e3cce3a55429
Removing intermediate container e3cce3a55429
 ---> 625e36647525
Step 5/15 : ENV Caffe2_DIR /usr/local/caffe2_build
 ---> Running in 8d08678a7384
Removing intermediate container 8d08678a7384
 ---> 3bfcf2de4261
Step 6/15 : ENV PYTHONPATH /usr/local/caffe2_build:${PYTHONPATH}
 ---> Running in 645f79d3248c
Removing intermediate container 645f79d3248c
 ---> ebe1c1a770c5
Step 7/15 : ENV LD_LIBRARY_PATH /usr/local/caffe2_build/lib:${LD_LIBRARY_PATH}
 ---> Running in 5c3526f9f769
Removing intermediate container 5c3526f9f769
 ---> f63eb5d59afa
Step 8/15 : RUN git clone https://github.com/facebookresearch/detectron /detectron
 ---> Running in a9eb1689eaf5
Cloning into '/detectron'...
Removing intermediate container a9eb1689eaf5
 ---> 2b05bb989954
Step 9/15 : RUN pip install -r /detectron/requirements.txt
 ---> Running in 11f4454933e4
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python2.7/dist-packages (from -r /detectron/requirements.txt (line 1))
Collecting pyyaml>=3.12 (from -r /detectron/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python2.7/dist-packages (from -r /detectron/requirements.txt (line 3))
Collecting opencv-python>=3.2 (from -r /detectron/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/0f/87/46f41c6673106030d835342e65133085c22cb36549a9ab883bb3cd3f00bb/opencv_python-3.4.1.15-cp27-cp27mu-manylinux1_x86_64.whl (24.9MB)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from -r /detectron/requirements.txt (line 5))
Collecting Cython (from -r /detectron/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/ae/02/4f218b527aee1a1ea5592ec2f75052f6dbc616f6107a1c7658f92ae19962/Cython-0.28.4-cp27-cp27mu-manylinux1_x86_64.whl (3.3MB)
Collecting mock (from -r /detectron/requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl (56kB)
Requirement already satisfied: scipy in /usr/local/lib/python2.7/dist-packages (from -r /detectron/requirements.txt (line 8))
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r /detectron/requirements.txt (line 3))
Requirement already satisfied: six>=1.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r /detectron/requirements.txt (line 3))
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r /detectron/requirements.txt (line 3))
Requirement already satisfied: subprocess32 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r /detectron/requirements.txt (line 3))
Requirement already satisfied: python-dateutil>=2.0 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r /detectron/requirements.txt (line 3))
Requirement already satisfied: backports.functools-lru-cache in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r /detectron/requirements.txt (line 3))
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python2.7/dist-packages (from matplotlib->-r /detectron/requirements.txt (line 3))
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from mock->-r /detectron/requirements.txt (line 7))
Collecting pbr>=0.11 (from mock->-r /detectron/requirements.txt (line 7))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/pbr/
  Downloading https://files.pythonhosted.org/packages/ae/d6/2ab389a3bf5fffd03069dacaddb0cdd531594abab5119f308527c0df53e6/pbr-4.1.0-py2.py3-none-any.whl (98kB)
Installing collected packages: pyyaml, opencv-python, Cython, pbr, mock
  Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
Successfully installed Cython-0.28.4 mock-2.0.0 opencv-python-3.4.1.15 pbr-4.1.0 pyyaml-3.13
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 11f4454933e4
 ---> c8aac9079b7d
Step 10/15 : RUN git clone https://github.com/cocodataset/cocoapi.git /cocoapi
 ---> Running in 04387a7e4f64
Cloning into '/cocoapi'...
Removing intermediate container 04387a7e4f64
 ---> f2c52cdc19a8
Step 11/15 : WORKDIR /cocoapi/PythonAPI
Removing intermediate container 26bcadd1282d
 ---> 3a573125e4b1
Step 12/15 : RUN make install
 ---> Running in c1f38bb021ff
# install pycocotools to the Python site-packages
python setup.py build_ext install
running build_ext
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
building 'pycocotools._mask' extension
creating build
creating build/common
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pycocotools
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I../common -I/usr/include/python2.7 -c ../common/maskApi.c -o build/temp.linux-x86_64-2.7/../common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
../common/maskApi.c: In function 'rleToBbox':
../common/maskApi.c:141:31: warning: 'xp' may be used uninitialized in this function [-Wmaybe-uninitialized]
       if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }
                               ^
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I../common -I/usr/include/python2.7 -c pycocotools/_mask.c -o build/temp.linux-x86_64-2.7/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pycocotools
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/../common/maskApi.o build/temp.linux-x86_64-2.7/pycocotools/_mask.o -o build/lib.linux-x86_64-2.7/pycocotools/_mask.so
running install
running bdist_egg
running egg_info
creating pycocotools.egg-info
writing requirements to pycocotools.egg-info/requires.txt
writing pycocotools.egg-info/PKG-INFO
writing top-level names to pycocotools.egg-info/top_level.txt
writing dependency_links to pycocotools.egg-info/dependency_links.txt
writing manifest file 'pycocotools.egg-info/SOURCES.txt'
reading manifest file 'pycocotools.egg-info/SOURCES.txt'
writing manifest file 'pycocotools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying pycocotools/__init__.py -> build/lib.linux-x86_64-2.7/pycocotools
copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-2.7/pycocotools
copying pycocotools/mask.py -> build/lib.linux-x86_64-2.7/pycocotools
copying pycocotools/coco.py -> build/lib.linux-x86_64-2.7/pycocotools
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-2.7/pycocotools/__init__.py -> build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-2.7/pycocotools/cocoeval.py -> build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-2.7/pycocotools/mask.py -> build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-2.7/pycocotools/coco.py -> build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-2.7/pycocotools/_mask.so -> build/bdist.linux-x86_64/egg/pycocotools
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/cocoeval.py to cocoeval.pyc
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/mask.py to mask.pyc
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/coco.py to coco.pyc
creating stub loader for pycocotools/_mask.so
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/_mask.py to _mask.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pycocotools-2.0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pycocotools-2.0-py2.7-linux-x86_64.egg
Copying pycocotools-2.0-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
Adding pycocotools 2.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pycocotools-2.0-py2.7-linux-x86_64.egg
Processing dependencies for pycocotools==2.0
Searching for matplotlib==2.1.1
Best match: matplotlib 2.1.1
Adding matplotlib 2.1.1 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for Cython==0.28.4
Best match: Cython 0.28.4
Adding Cython 0.28.4 to easy-install.pth file
Installing cython script to /usr/local/bin
Installing cygdb script to /usr/local/bin
Installing cythonize script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages
Searching for setuptools==20.7.0
Best match: setuptools 20.7.0
Adding setuptools 20.7.0 to easy-install.pth file
Installing easy_install script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Searching for pyparsing==2.2.0
Best match: pyparsing 2.2.0
Adding pyparsing 2.2.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for backports.functools-lru-cache==1.4
Best match: backports.functools-lru-cache 1.4
Adding backports.functools-lru-cache 1.4 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for python-dateutil==2.6.1
Best match: python-dateutil 2.6.1
Adding python-dateutil 2.6.1 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for subprocess32==3.2.7
Best match: subprocess32 3.2.7
Adding subprocess32 3.2.7 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for pytz==2017.3
Best match: pytz 2017.3
Adding pytz 2017.3 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for numpy==1.14.0
Best match: numpy 1.14.0
Adding numpy 1.14.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for pycocotools==2.0
rm -rf build
Removing intermediate container c1f38bb021ff
 ---> a3695c60745b
Step 13/15 : WORKDIR /detectron
Removing intermediate container decee67b8688
 ---> 80f0996c5d89
Step 14/15 : RUN make
 ---> Running in 3c64c55eab25
python2 setup.py develop --user
Compiling detectron/utils/cython_bbox.pyx because it changed.
Compiling detectron/utils/cython_nms.pyx because it changed.
[1/2] Cythonizing detectron/utils/cython_bbox.pyx
[2/2] Cythonizing detectron/utils/cython_nms.pyx
running develop
running egg_info
creating Detectron.egg-info
writing Detectron.egg-info/PKG-INFO
writing top-level names to Detectron.egg-info/top_level.txt
writing dependency_links to Detectron.egg-info/dependency_links.txt
writing manifest file 'Detectron.egg-info/SOURCES.txt'
reading manifest file 'Detectron.egg-info/SOURCES.txt'
writing manifest file 'Detectron.egg-info/SOURCES.txt'
running build_ext
building 'detectron.utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/detectron
creating build/temp.linux-x86_64-2.7/detectron/utils
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c detectron/utils/cython_bbox.c -o build/temp.linux-x86_64-2.7/detectron/utils/cython_bbox.o -Wno-cpp
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/detectron
creating build/lib.linux-x86_64-2.7/detectron/utils
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/detectron/utils/cython_bbox.o -o build/lib.linux-x86_64-2.7/detectron/utils/cython_bbox.so
building 'detectron.utils.cython_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c detectron/utils/cython_nms.c -o build/temp.linux-x86_64-2.7/detectron/utils/cython_nms.o -Wno-cpp
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/detectron/utils/cython_nms.o -o build/lib.linux-x86_64-2.7/detectron/utils/cython_nms.so
copying build/lib.linux-x86_64-2.7/detectron/utils/cython_bbox.so -> detectron/utils
copying build/lib.linux-x86_64-2.7/detectron/utils/cython_nms.so -> detectron/utils
Creating /root/.local/lib/python2.7/site-packages/Detectron.egg-link (link to .)
Adding Detectron 0.0.0 to easy-install.pth file

Installed /detectron
Processing dependencies for Detectron==0.0.0
Finished processing dependencies for Detectron==0.0.0
Removing intermediate container 3c64c55eab25
 ---> 676e2eb52e9a
Step 15/15 : RUN make ops
 ---> Running in 87320202f075
mkdir -p build && cd build && cmake .. && make -j6
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "FindCaffe2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Caffe2", but
  CMake did not find one.

  Could not find a package configuration file provided by "Caffe2" with any
  of the following names:

    Caffe2Config.cmake
    caffe2-config.cmake

  Add the installation prefix of "Caffe2" to CMAKE_PREFIX_PATH or set
  "Caffe2_DIR" to a directory containing one of the above files.  If "Caffe2"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/detectron/build/CMakeFiles/CMakeOutput.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1
The command '/bin/sh -c make ops' returned a non-zero code: 2

**Comment by ir413** [comment] 2018-07-19 12:30
Hi @hxtkyne, from the stack trace it seems that you modified the detectron docker file. We recommend using the original docker file provided in the detectron repo. This also seems like a duplicate of #569.

**Closed by ir413** 2018-07-19 12:30 UTC
