### ISSUE TITLE
 tools/train_net.py  1gpu failed

### ISSUE THREAD

**Issue by cableyang** [facebookresearch/Detectron#594] opened 2018-07-31 13:11 UTC
### Expected results
finish trainning 

What did you expect to see?
finish trainning 

### Actual results
*** Aborted at 1533024434 (unix time) try "date -d @1533024434" if you are using GNU date ***
PC: @     0x7f12a9daf545 (unknown)
*** SIGSEGV (@0x18) received by PID 864 (TID 0x7f11b5dff700) from PID 24; stack trace: ***
    @     0x7f12aa108390 (unknown)
    @     0x7f12a9daf545 (unknown)
    @     0x7f12a9db1184 __libc_malloc
    @     0x7f12a154c8ef NpyIter_AdvancedNew
    @     0x7f128d031816 PyUFunc_GenericFunction
    @     0x7f128d032757 ufunc_generic_call
    @           0x4b0c93 PyObject_Call
    @           0x4b97a2 PyObject_CallFunctionObjArgs
    @     0x7f12a15551cb array_add
    @           0x50fbb8 PyNumber_Add
    @           0x4ca4a3 PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4de69e (unknown)
    @           0x4b0c93 PyObject_Call
    @           0x4f452e (unknown)
    @           0x4b0c93 PyObject_Call
    @           0x4ce540 PyEval_CallObjectWithKeywords
    @     0x7f129e828067 pybind11::detail::object_api<>::operator()<>()
    @     0x7f129e829eb1 caffe2::python::PythonOpBase<>::RunOnDevice()
    @     0x7f129e7ef20b caffe2::Operator<>::Run()
    @     0x7f129e83bff8 _ZN6caffe213GPUFallbackOpINS_6python8PythonOpINS_10CPUContextELb0EEENS_11SkipIndicesIJEEEE11RunOnDeviceEv
    @     0x7f129e8385b5 caffe2::Operator<>::Run()
    @     0x7f1282d938fa caffe2::DAGNet::RunAt()
    @     0x7f1282d927ec caffe2::DAGNetBase::WorkerFunction()
    @     0x7f12a3df1c80 (unknown)
    @     0x7f12aa0fe6ba start_thread
    @     0x7f12a9e3441d clone
    @                0x0 (unknown)

What did you observe instead?

### Detailed steps to reproduce
The command that you ran
 python tools/train_net.py --cfg ./configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN_fashion.yaml OUTPUT_DIR./test_output/

### System information
nivida-docker  detectron:c2-cuda9-cudnn7
* Operating system: Ubuntu16.04 
* Compiler version: 
* CUDA version: 9.0
* cuDNN version: 7.0
* NVIDIA driver version: 390.77
* GPU models (for all devices if they are not all the same): 
* `PYTHONPATH` environment variable: Docker detectron:c2-cuda9-cudnn7
* `python --version` output: 2.7.12
* Anything else that seems relevant: train steps and 56000 for one gpu train stop

**Comment by gadcam** [comment] 2018-07-31 21:52
I think you should comment on #578, you can also check https://github.com/facebookresearch/Detectron/issues/578#issuecomment-406867295 which lists duplicate and linked issues.

**Comment by cableyang** [comment] 2018-08-02 02:48
I changed my learning rate,slow down then can try

**Comment by RainHxj** [comment] 2018-08-23 08:13
oh i encounter the same question.

**Comment by ir413** [comment] 2018-09-18 17:32
Closing as this seems like a duplicate of #578.

**Closed by ir413** 2018-09-18 17:32 UTC
