### ISSUE TITLE
Get lower AP in testing trained model from model zoo

### ISSUE THREAD

**Issue by suica** [facebookresearch/Detectron#517] opened 2018-06-23 09:31 UTC
Hi!
I used Detectron for several months (so I am not using the latest version of Detectron) and everything went well. Recently I downloaded many **trained** models from `model zoo` and test them myself but got `AP`'s being obviously lower than values claimed in `MODEL_ZOO.md`.

In `GETTING_STARTED.md`, a command testing the model `e2e_mask_rcnn_R-101-FPN_2x` is provided.
I ran it but got different result.
### Expected results

e2e_mask_rcnn_R-101-FPN_2x (model id = 35861858) 
should have `bbox AP` = 40.9% and `segm AP` = 36.4% (values are from `MODEL_ZOO.md`).

### Actual results

```
INFO task_evaluation.py: 182: copypaste: Task: box
INFO task_evaluation.py: 185: copypaste: AP,AP50,AP75,APs,APm,APl
INFO task_evaluation.py: 186: copypaste: 0.3571,0.5709,0.3934,0.2241,0.4080,0.4277
INFO task_evaluation.py: 182: copypaste: Task: mask
INFO task_evaluation.py: 185: copypaste: AP,AP50,AP75,APs,APm,APl
INFO task_evaluation.py: 186: copypaste: 0.3242,0.5399,0.3427,0.1582,0.3700,0.4758
```

### Detailed steps to reproduce

I copied command from `GETTING_STARTED.md` as
```
python2 tools/test_net.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --multi-gpu-testing \
    TEST.WEIGHTS https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    NUM_GPUS $N
```
then replaced `$N` by 4, getting
```
python2 tools/test_net.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --multi-gpu-testing \
    TEST.WEIGHTS https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    NUM_GPUS 4
```
Then I ran the modified command and see the result described above.

### System information

* Operating system: Ubuntu 16.04.1
* Compiler version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
* CUDA version: 8.0.61
* cuDNN version: 6
* NVIDIA driver version: 384.130
* GPU models: Titan Xp * 4 
* `PYTHONPATH` environment variable: `/DATACENTER1/test/caffe2/build`
* `python --version` output: `Python 2.7.12`
* I didn't modify `e2e_mask_rcnn_R-101-FPN_2x.yaml` nor any code in Detectron.

**Comment by rbgirshick** [comment] 2018-06-25 16:06
@suica can you provide the full stdout and stderr log files (provide a link to them)? When I run the command I am able to reproduce the model zoo results.

**Comment by rbgirshick** [comment] 2018-06-27 14:11
Cannot reproduce and no updates. Closing.

**Closed by rbgirshick** 2018-06-27 14:11 UTC
